Level 1 - 마무리
Ho-Tea/Blog pull request #1
Opened 2023-06-16 03:23 UTC by Ho-Tea

블로그 포스트들의 콘솔 출력과 내용들이 메모리에 저장되는 간단한 어플리케이션

2023-06-16 07:27 UTC, 0chil requested changes
안녕하세요 주호짱
방금 막 작업을 끝내서 그런지 아직은 코드에 불필요한 부분이 많다고 느껴지네요 🥲
먼저 조금 덜어낸 후 리뷰를 드리는 게 더 의미있는 리뷰가 될 것 같아 우선 변경 요청드립니다.
1. 불필요한 구조나 추상화 덜어내기
2. 의도가 더 잘 드러나는 코드 작성하기(메서드명, 클래스명, 변수명 등)

커멘트도 몇 개 달아놓으니 여러 방면으로 고민해보시고, 궁금한 점은 카톡 주십쇼!

2023-06-29 13:16 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/BlogApplication.java
> +        blog.init();
맞는말입니다! BlogController의 인스턴스를 생성한후 무조건 init함수를 호출해 Controller를 초기화해야한다면, 굳이 일련의 행동을 나누어서 두번하는 것은 혼란을 야기할 수 있을 것 같습니다 수정하였습니다!

2023-06-29 13:23 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/constant/Blog.java
> +    }
함수 네이밍 컨벤션을 지켜 함수 이름이 곧 주석이 되게끔 다시 구성하는 것이 맞다고 생각합니다 of 보다는 is가 더 명확하게 다가오는것 같습니다 수정했습니다!

2023-06-29 14:01 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/constant/Blog.java
> +    public static Blog status = Blog.WAIT;
Enum은 열거형으로 서로 연관된 상수들의 집합을 의미하는데 따로 status라는 상태를 유지하는 것은 맞지 않다고 생각됩니다! 즉 상태와 행위를 한곳에서 처리할 수 있는 이점이 Enum에 존재하지만 그 상태라는것이 위의 status변수가 의미하는 상태와는 다른 것임을 깨달았습니다 수정했습니다!

2023-06-29 14:06 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/constant/Blog.java
> +    }
위의 command 함수 부분은 실행할 수 있는 명령들의 집합을 반환하는 메서드인데 받은 피드백을 통해 Enum이 상태를 가지지 않게끔 구성하면 Enum자체적으로 존재하는 values()메서드를 호출하면 대체가능한 메서드라 삭제하였습니다!

2023-06-29 14:40 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/controller/BlogController.java
> +    }
맞습니다! 인자나 메서드의 반환을 통해 무엇을, 왜 전달하려는지 명확히 할 필요가 있을 것 같습니다
위의 코드는 command내부에서 Blog내부에서 유지하던 상태값을 해당하는 명령으로 바꾸는 과정이 일어나는데, 
이과정은 몰래의사를 전달하여 가시적으로 어떤 행위가 일어나는지 잘 알 수 없고, 
하나의 메서드가 하나의 일만을 수행하는 SRP조차도 지키지 못하는 것 같아 수정하였습니다!

2023-06-29 15:17 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/constant/ContentType.java
> +    }
충분히 매력적으로 보이기는합니다
기존 코드보다 가독성면에서 더 잘 읽히는 느낌이 들기는 합니다만 변경하는 이유가 혹시 메모리효율의 관점(static)이 아닌 오로지 가독성면에서 더 잘 읽히는 이유로 변경하는 건가요?

2023-06-30 04:31 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/vo/ContentVo.java
아직 값 자체에 의미가 있는 VO와 전달될 데이터를 보존해야 하는 DTO에 대한 이해가 부족한것 같습니다
너무 어렵게 생각하지 않고 DTO는 전달되는 데이터를 의미하고, VO는 값 자체, 예를 들어서 돈 만원을 생각하여 적용하니 더 이해가 쉬워졌습니다
위의 ContentVO의 경우 ContentType과 CategoryDto와 같은 데이터를 전달하는 역할을 하므로 VO보다는 DTO로 하는 것이 더 맞는것 같습니다 수정하였습니다!

2023-06-30 04:52 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/vo/ContentVo.java
여기서 생긴 궁금증은 ContentVo → ContentDto로 변환했을 때 이미 Content라는 인터페이스가 존재하여 ContentDto는 Content라는 인터페이스에 관한 데이터만을 담고있어야 되지 않을까?(Content로 이름이 동일하기 때문에)라는 궁금증입니다 
ContentDto는 ContentType과 CategoryDto 두개의 데이터를 담고 있어 기존 Content보다 많은 양의 데이터를 내포하고 있습니다 CategoryDto와 Category의 경우 1대1로 매핑되고, 서로 변환될 수 있는 관계로 유지되지만 Content와 ContentDto의 경우에는 1대1로 매핑이 되지 않을 뿐더러 서로 변환 될 수 있는 관계가 아닙니다
ContentDto의 이름을 다른 것으로 변경해야 할까요?? 아니면 ContentDto라고 그냥 사용해도 될까요?

2023-06-30 05:40 UTC, Ho-Tea commented on blog/src/main/java/dev/be/blog/controller/BlogController.java
> +        }
확실히 저 부분이 제일 마음에 안들었습니다
분기처리를 저런식으로 구성하면 가독성도 떨어지고 무엇을 말하는지 직관적으로 알아들을 수가 없기 때문입니다
따라서, 분기처리 대신 함수를 호출하여 함수의 이름만으로도 어떤 일을 행하는지 쉽게 알수있는 방식으로 리팩터링을 진행하여 수정하였습니다!
상태와 행위를 한곳에 저장할 수 있는 Enum의 특징을 살려 write메서드를 Blog(Enum)에서 바로 실행 시키고 싶었지만 그러면 Blog가 BlogController를 알고 있고, 인스턴스를 유지해야 하므로 너무 의존하는 관계가 성립이 되어 하지 않았습니다!

모든 부분 피드백 반영하여 수정하였습니다
감사합니다!

2023-07-02 12:38 UTC, 0chil commented on blog/src/main/java/dev/be/blog/dto/PostDto.java
> +
?? 님뭐함?

2023-07-07 13:32 UTC, Ho-Tea commented
아직 마음에 드는 코드가 나오지 않았지만 뼈와 살을 붙이는 과정을 몸으로 겪고 추후에 리팩토링 과정을 겪으려 한다..!

2023-07-07 13:33 UTC, merged